### ISSUE TITLE
Installing test packages

### ISSUE THREAD

**Issue by carlskii** [project-flogo/core#141]
```
go version go1.13.1 darwin/amd64
```

I'm following the tutorial for creating my own activity and get the following error when trying to in install the test package: 

```
 go get github.com/project-flogo/core/support/test                            
# github.com/project-flogo/core/support/test
../../../go/src/github.com/project-flogo/core/support/test/trigger.go:33:21: not enough arguments in call to tConfig.FixUp
	have (*trigger.Metadata)
	want (*trigger.Metadata, resolve.CompositeResolver)
```

If I ignore the test for now and try to install my activity as per the tutorial, it tells me that I have a missing `flogo.json` file.

```
flogo install github.com/carlskii/myNewActivity                                                                          ✔  at 
Error validating project: not a valid flogo app project directory, missing flogo.json
```

**Comment by skothari-tibco** [comment]
For the first one, I think it's a versioning issue, Can you make sure you are using updated version of the flogo core repo?

 For the second one, The `flogo` command should be called under the Flogo App Dir. 

Hope this helps.

**Comment by carlskii** [comment]
Thanks for the response. So I've sorted the second issue. However, as far as I can see I'm using the latest versions of the flogo core repo. Still hitting the same issue though.

**Comment by carlskii** [comment]
Thanks for the response. So implemented the change in trigger.go. However, I'm now hitting the following issue:

```
$go test                                                              
# _/Users/cbourne/local_development/flogo/myNewActivity [_/Users/cbourne/local_development/flogo/myNewActivity.test]
./activity_test.go:27:23: cannot use tc (type *test.TestActivityContext) as type activity.Context in argument to act.Eval:
	*test.TestActivityContext does not implement activity.Context (missing GetTracingContext method)
FAIL	_/Users/cbourne/local_development/flogo/myNewActivity [build failed]
```

**Comment by skothari-tibco** [comment]
I have updated the changes and tested it. It should work now. Thank you.

**Comment by carlskii** [comment]
Thanks. Just cleared down everything and tried to install the prereqs for the test but I'm still getting this error. 

```
 go get github.com/project-flogo/core/support/test                            
# github.com/project-flogo/core/support/test
../../../go/src/github.com/project-flogo/core/support/test/trigger.go:33:21: not enough arguments in call to tConfig.FixUp
	have (*trigger.Metadata)
	want (*trigger.Metadata, resolve.CompositeResolver)
```

**Comment by skothari-tibco** [comment]
Oh. The Pull Request #142  still needs to be merged. Should be done by today.

**Comment by carlskii** [comment]
Thanks - So some progress. But get this now when I try to run the test against the example activity.

```
$go test                                                       
# github.com/project-flogo/core/support/test
../../support/test/context.go:227:51: undefined: trace
FAIL	github.com/project-flogo/core/examples/activity [build failed]
```

**Comment by carlskii** [comment]
Looks like the recent commits have resolved this. Thank you for all your work!
